# Define variables for server configuration
server_ip = "192.168.56.110"

server_hostname = "nenvoyS"

image = "generic/alpine311"

memory = "2048"
cpus = 2

Vagrant.configure("2") do |config|
  # Use VirtualBox as the provider
  config.vm.provider "virtualbox" do |vb|
    vb.memory = memory
    vb.cpus = cpus
  end

  # Define a virtual machine with the specified settings
  config.vm.define server_hostname do |server|
    server.vm.box = image
    server.vm.hostname = server_hostname
    server.vm.synced_folder ".", "/vagrant"
    server.vm.network "private_network", ip: server_ip
    server.vm.provision "shell", privileged: true, path: "scripts/k3s_master.sh", args: [server_ip]
  end
end
